# Basic
title: 黄鹏
subtitle: 个人站
description: 遇事须上虎背~
# 头像里面的标题
avatarTitle: PPPHUANG
# 头像里面的描述
avatarDesc: PHP Coder
url: "http://ppphuang.github.io"

# Comment
comment:
    # disqus: leopard
    # duoshuo: leopard 
    # cloudTie: leopard

# Social
social:
    weibo: u/3907394215?is_all=1
    github: PPPHUANG
    # twitter: 
    mail: huangpengr@gmail.com

# 百度统计 
# 使用博客模板请去掉或者更换 id   

# Google Analytics
# 使用博客模板请去掉或者更换 id


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


